apiVersion: apps/v1
kind: Deployment
metadata:
  name: orquesting
  annotations:
    kubernetes.io/change-cause: "Core version V1, nothing changes"
  labels:
    app: prod-deloyment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prod
  template:
    metadata:
      labels:
        app: prod
    spec:
      imagePullSecrets:
        - name: secret_any
      containers:
        - name: backend
          image: anyregistry1.0.0
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          envFrom:
            - configMapRef:
                name: configmap
            - secretRef:
                name: app-secret
        - name: db
          image: postgres:13-alpine
          ports:
            - containerPort: 5432
          resources:
            requests: 
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          envFrom:
            - configMapRef:
                name: configmap
            - secretRef:
                name: app-secret
        - name: redis
          image: redis:6-alpine
          ports:
            - containerPort: 6379
          resources:
            requests: 
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: configmap
            - secretRef:
                name: app-secret
        - name: exchange
          image: legrev/bcv-exchange-rates-new:latest
          ports:
            - containerPort: 8000
          resources:
            requests: 
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: configmap
            - secretRef:
                name: app-secret
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: pgdata
---
apiVersion: v1
kind: Service
metadata:
  name: prod-svc
spec:
  type: NodePort
  selector:
    app: prod
  ports:
    - protocol: TCP
      name: db
      port: 5432
      targetPort: 5432
    - protocol: TCP
      name: backend
      port: 3000
      targetPort: 3000
      

  