#This create a secret as .env, but in kubernetes you have to do manual, cause we cannot use .env file, or set environment variables in the deployment, it hashes the values
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: default
type: Opaque
stringData:
  DATABASE_BIT_HOST: "localhost"