apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-back
  labels:
    app: rs-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      -  name: web
         image: nginx:1.23
