apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: secret-docker
      containers:
        - name: frontend-container
          image: anyregistry:0.0.2
          ports:
            - containerPort: 3001
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          envFrom:
            - configMapRef:
                name: frontend-configmap
            - secretRef:
                name: frontend-secret